### ISSUE TITLE
Failed connecting to Hive metastore, with buckets on Cloudian

### ISSUE THREAD

**Issue by GitTInto** [joshuarobinson/presto-on-k8s#5]
I have trino installed on K8s - 1 pod coordinator, 2 pods workers, 1 pod hive metastore connecting to Cloudian hyperstore

but when i connect and do show tables i get below error

trino --server 10.5.74.220:8080 --catalog hive --schema default
trino:default> 
trino:default> show tables;
Query 20220831_000942_00019_5adaa failed: Failed connecting to Hive metastore: [metastore:9083]

Can you give me some advice how to resolve this.

Appreciate any help

**Comment by GitTInto** [comment]
Here is the error log with --debug option



trino:default> show schemas;
Query 20220831_000050_00000_5adaa [RUNNING] i[0 0B 0B] o[0 0B 0B] splits[0/6/0]
Query 20220831_000050_00000_5adaa, FAILED, 3 nodes
http://ip/ here:8080/ui/query.html?20220831_000050_00000_5adaa
Splits: 6 total, 0 done (0.00%)
CPU Time: 0.0s total, 0 rows/s, 0B/s, 0% active
Per Node: 0.0 parallelism, 0 rows/s, 0B/sParallelism: 0.0
Peak Memory: 0B19.44 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20220831_000050_00000_5adaa failed: Failed connecting to Hive metastore: [metastore:9083]
io.trino.spi.TrinoException: Failed connecting to Hive metastore: [metastore:9083]
at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.getAllDatabases(ThriftHiveMetastore.java:269)
at io.trino.plugin.hive.metastore.thrift.BridgingHiveMetastore.getAllDatabases(BridgingHiveMetastore.java:90)
at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.loadAllDatabases(CachingHiveMetastore.java:255)
at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.lambda$new$0(CachingHiveMetastore.java:152)
at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:169)
at io.trino.collect.cache.EvictableCache$TokenCacheLoader.load(EvictableCache.java:390)
at io.trino.collect.cache.EvictableCache$TokenCacheLoader.load(EvictableCache.java:376)
at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3533)
at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2282)
at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159)
at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
at com.google.common.cache.LocalCache.get(LocalCache.java:3966)
at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3989)
at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4950)
at io.trino.collect.cache.EvictableCache.get(EvictableCache.java:129)
at com.google.common.cache.AbstractLoadingCache.getUnchecked(AbstractLoadingCache.java:51)
at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.get(CachingHiveMetastore.java:216)
at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.getAllDatabases(CachingHiveMetastore.java:250)
at io.trino.plugin.hive.HiveMetastoreClosure.getAllDatabases(HiveMetastoreClosure.java:70)
at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.getAllDatabases(SemiTransactionalHiveMetastore.java:201)
at io.trino.plugin.hive.HiveMetadata.listSchemaNames(HiveMetadata.java:420)
at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.listSchemaNames(ClassLoaderSafeConnectorMetadata.java:174)
at io.trino.metadata.MetadataManager.listSchemaNames(MetadataManager.java:235)
at io.trino.metadata.MetadataListing.listSchemas(MetadataListing.java:99)
at io.trino.metadata.MetadataListing.listSchemas(MetadataListing.java:94)
at io.trino.connector.informationschema.InformationSchemaPageSource.addSchemataRecords(InformationSchemaPageSource.java:316)
at io.trino.connector.informationschema.InformationSchemaPageSource.buildPages(InformationSchemaPageSource.java:225)
at io.trino.connector.informationschema.InformationSchemaPageSource.getNextPage(InformationSchemaPageSource.java:183)
at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:311)
at io.trino.operator.Driver.processInternal(Driver.java:388)
at io.trino.operator.Driver.lambda$processFor$9(Driver.java:292)
at io.trino.operator.Driver.tryWithLock(Driver.java:693)
at io.trino.operator.Driver.processFor(Driver.java:285)
at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1092)
at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:488)
at io.trino.$gen.Trino_374____20220830_235636_2.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.thrift.TException: Failed connecting to Hive metastore: [metastore:9083]
at io.trino.plugin.hive.metastore.thrift.StaticMetastoreLocator.createMetastoreClient(StaticMetastoreLocator.java:117)
at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.createMetastoreClient(ThriftHiveMetastore.java:2081)
at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.lambda$getAllDatabases$0(ThriftHiveMetastore.java:263)
at io.trino.plugin.hive.metastore.thrift.ThriftMetastoreApiStats.lambda$wrap$0(ThriftMetastoreApiStats.java:42)
at io.trino.plugin.hive.util.RetryDriver.run(RetryDriver.java:130)
at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.getAllDatabases(ThriftHiveMetastore.java:262)
... 39 more
Suppressed: org.apache.thrift.TException: Failed connecting to Hive metastore: [metastore:9083]
... 45 more
Caused by: org.apache.thrift.transport.TTransportException: metastore:9083: java.net.ConnectException: Connection refused (Connection refused)
at io.trino.plugin.hive.metastore.thrift.Transport.rewriteException(Transport.java:96)
at io.trino.plugin.hive.metastore.thrift.Transport.create(Transport.java:55)
at io.trino.plugin.hive.metastore.thrift.DefaultThriftMetastoreClientFactory.createTransport(DefaultThriftMetastoreClientFactory.java:110)
at io.trino.plugin.hive.metastore.thrift.DefaultThriftMetastoreClientFactory.create(DefaultThriftMetastoreClientFactory.java:97)
at io.trino.plugin.hive.metastore.thrift.StaticMetastoreLocator.getClient(StaticMetastoreLocator.java:123)
at io.trino.plugin.hive.metastore.thrift.StaticMetastoreLocator.createMetastoreClient(StaticMetastoreLocator.java:109)
... 44 more
Caused by: org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused (Connection refused)
at io.trino.plugin.hive.metastore.thrift.Transport.createRaw(Transport.java:89)
at io.trino.plugin.hive.metastore.thrift.Transport.create(Transport.java:47)
... 48 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
at java.base/java.net.Socket.connect(Socket.java:615)
at io.trino.plugin.hive.metastore.thrift.Transport.createRaw(Transport.java:70)
... 49 more
Suppressed: org.apache.thrift.TException: Failed connecting to Hive metastore: [metastore:9083]
... 45 more
Caused by: org.apache.thrift.transport.TTransportException: metastore:9083: java.net.ConnectException: Connection refused (Connection refused)
at io.trino.plugin.hive.metastore.thrift.Transport.rewriteException(Transport.java:96)
at io.trino.plugin.hive.metastore.thrift.Transport.create(Transport.java:55)
at io.trino.plugin.hive.metastore.thrift.DefaultThriftMetastoreClientFactory.createTransport(DefaultThriftMetastoreClientFactory.java:110)
at io.trino.plugin.hive.metastore.thrift.DefaultThriftMetastoreClientFactory.create(DefaultThriftMetastoreClientFactory.java:97)
at io.trino.plugin.hive.metastore.thrift.StaticMetastoreLocator.getClient(StaticMetastoreLocator.java:123)
at io.trino.plugin.hive.metastore.thrift.StaticMetastoreLocator.createMetastoreClient(StaticMetastoreLocator.java:109)
... 44 more
Caused by: org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused (Connection refused)
at io.trino.plugin.hive.metastore.thrift.Transport.createRaw(Transport.java:89)
at io.trino.plugin.hive.metastore.thrift.Transport.create(Transport.java:47)
... 48 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
at java.base/java.net.Socket.connect(Socket.java:615)
at io.trino.plugin.hive.metastore.thrift.Transport.createRaw(Transport.java:70)
... 49 more
Suppressed: org.apache.thrift.TException: Failed connecting to Hive metastore: [metastore:9083]
... 45 more
Caused by: org.apache.thrift.transport.TTransportException: metastore:9083: java.net.ConnectException: Connection refused (Connection refused)
at io.trino.plugin.hive.metastore.thrift.Transport.rewriteException(Transport.java:96)
at io.trino.plugin.hive.metastore.thrift.Transport.create(Transport.java:55)
at io.trino.plugin.hive.metastore.thrift.DefaultThriftMetastoreClientFactory.createTransport(DefaultThriftMetastoreClientFactory.java:110)
at io.trino.plugin.hive.metastore.thrift.DefaultThriftMetastoreClientFactory.create(DefaultThriftMetastoreClientFactory.java:97)
at io.trino.plugin.hive.metastore.thrift.StaticMetastoreLocator.getClient(StaticMetastoreLocator.java:123)
at io.trino.plugin.hive.metastore.thrift.StaticMetastoreLocator.createMetastoreClient(StaticMetastoreLocator.java:109)
... 44 more
Caused by: org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused (Connection refused)
at io.trino.plugin.hive.metastore.thrift.Transport.createRaw(Transport.java:89)
at io.trino.plugin.hive.metastore.thrift.Transport.create(Transport.java:47)
... 48 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
at java.base/java.net.Socket.connect(Socket.java:615)
at io.trino.plugin.hive.metastore.thrift.Transport.createRaw(Transport.java:70)
... 49 more
Suppressed: org.apache.thrift.TException: Failed connecting to Hive metastore: [metastore:9083]
... 45 more
Caused by: org.apache.thrift.transport.TTransportException: metastore:9083: java.net.ConnectException: Connection refused (Connection refused)
at io.trino.plugin.hive.metastore.thrift.Transport.rewriteException(Transport.java:96)
at io.trino.plugin.hive.metastore.thrift.Transport.create(Transport.java:55)
at io.trino.plugin.hive.metastore.thrift.DefaultThriftMetastoreClientFactory.createTransport(DefaultThriftMetastoreClientFactory.java:110)
at io.trino.plugin.hive.metastore.thrift.DefaultThriftMetastoreClientFactory.create(DefaultThriftMetastoreClientFactory.java:97)
at io.trino.plugin.hive.metastore.thrift.StaticMetastoreLocator.getClient(StaticMetastoreLocator.java:123)
at io.trino.plugin.hive.metastore.thrift.StaticMetastoreLocator.createMetastoreClient(StaticMetastoreLocator.java:109)
... 44 more
Caused by: org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused (Connection refused)
at io.trino.plugin.hive.metastore.thrift.Transport.createRaw(Transport.java:89)
at io.trino.plugin.hive.metastore.thrift.Transport.create(Transport.java:47)
... 48 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
at java.base/java.net.Socket.connect(Socket.java:615)
at io.trino.plugin.hive.metastore.thrift.Transport.createRaw(Transport.java:70)
... 49 more
Suppressed: org.apache.thrift.TException: Failed connecting to Hive metastore: [metastore:9083]
... 45 more
Caused by: org.apache.thrift.transport.TTransportException: metastore:9083: java.net.ConnectException: Connection refused (Connection refused)
at io.trino.plugin.hive.metastore.thrift.Transport.rewriteException(Transport.java:96)
at io.trino.plugin.hive.metastore.thrift.Transport.create(Transport.java:55)
at io.trino.plugin.hive.metastore.thrift.DefaultThriftMetastoreClientFactory.createTransport(DefaultThriftMetastoreClientFactory.java:110)
at io.trino.plugin.hive.metastore.thrift.DefaultThriftMetastoreClientFactory.create(DefaultThriftMetastoreClientFactory.java:97)
at io.trino.plugin.hive.metastore.thrift.StaticMetastoreLocator.getClient(StaticMetastoreLocator.java:123)
at io.trino.plugin.hive.metastore.thrift.StaticMetastoreLocator.createMetastoreClient(StaticMetastoreLocator.java:109)
... 44 more
Caused by: org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused (Connection refused)
at io.trino.plugin.hive.metastore.thrift.Transport.createRaw(Transport.java:89)
at io.trino.plugin.hive.metastore.thrift.Transport.create(Transport.java:47)
... 48 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
at java.base/java.net.Socket.connect(Socket.java:615)
at io.trino.plugin.hive.metastore.thrift.Transport.createRaw(Transport.java:70)
... 49 more
Suppressed: org.apache.thrift.TException: Failed connecting to Hive metastore: [metastore:9083]
... 45 more
Caused by: org.apache.thrift.transport.TTransportException: metastore:9083: java.net.ConnectException: Connection refused (Connection refused)
at io.trino.plugin.hive.metastore.thrift.Transport.rewriteException(Transport.java:96)
at io.trino.plugin.hive.metastore.thrift.Transport.create(Transport.java:55)
at io.trino.plugin.hive.metastore.thrift.DefaultThriftMetastoreClientFactory.createTransport(DefaultThriftMetastoreClientFactory.java:110)
at io.trino.plugin.hive.metastore.thrift.DefaultThriftMetastoreClientFactory.create(DefaultThriftMetastoreClientFactory.java:97)
at io.trino.plugin.hive.metastore.thrift.StaticMetastoreLocator.getClient(StaticMetastoreLocator.java:123)
at io.trino.plugin.hive.metastore.thrift.StaticMetastoreLocator.createMetastoreClient(StaticMetastoreLocator.java:109)
... 44 more
Caused by: org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused (Connection refused)
at io.trino.plugin.hive.metastore.thrift.Transport.createRaw(Transport.java:89)
at io.trino.plugin.hive.metastore.thrift.Transport.create(Transport.java:47)
... 48 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
at java.base/java.net.Socket.connect(Socket.java:615)
at io.trino.plugin.hive.metastore.thrift.Transport.createRaw(Transport.java:70)
... 49 more
Suppressed: org.apache.thrift.TException: Failed connecting to Hive metastore: [metastore:9083]
... 45 more
Caused by: org.apache.thrift.transport.TTransportException: metastore:9083: java.net.ConnectException: Connection refused (Connection refused)
at io.trino.plugin.hive.metastore.thrift.Transport.rewriteException(Transport.java:96)
at io.trino.plugin.hive.metastore.thrift.Transport.create(Transport.java:55)
at io.trino.plugin.hive.metastore.thrift.DefaultThriftMetastoreClientFactory.createTransport(DefaultThriftMetastoreClientFactory.java:110)
at io.trino.plugin.hive.metastore.thrift.DefaultThriftMetastoreClientFactory.create(DefaultThriftMetastoreClientFactory.java:97)
at io.trino.plugin.hive.metastore.thrift.StaticMetastoreLocator.getClient(StaticMetastoreLocator.java:123)
at io.trino.plugin.hive.metastore.thrift.StaticMetastoreLocator.createMetastoreClient(StaticMetastoreLocator.java:109)
... 44 more
Caused by: org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused (Connection refused)
at io.trino.plugin.hive.metastore.thrift.Transport.createRaw(Transport.java:89)
at io.trino.plugin.hive.metastore.thrift.Transport.create(Transport.java:47)
... 48 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
at java.base/java.net.Socket.connect(Socket.java:615)
at io.trino.plugin.hive.metastore.thrift.Transport.createRaw(Transport.java:70)
... 49 more
Suppressed: org.apache.thrift.TException: Failed connecting to Hive metastore: [metastore:9083]
... 45 more
Caused by: org.apache.thrift.transport.TTransportException: metastore:9083: java.net.ConnectException: Connection refused (Connection refused)
at io.trino.plugin.hive.metastore.thrift.Transport.rewriteException(Transport.java:96)
at io.trino.plugin.hive.metastore.thrift.Transport.create(Transport.java:55)
at io.trino.plugin.hive.metastore.thrift.DefaultThriftMetastoreClientFactory.createTransport(DefaultThriftMetastoreClientFactory.java:110)
at io.trino.plugin.hive.metastore.thrift.DefaultThriftMetastoreClientFactory.create(DefaultThriftMetastoreClientFactory.java:97)
at io.trino.plugin.hive.metastore.thrift.StaticMetastoreLocator.getClient(StaticMetastoreLocator.java:123)
at io.trino.plugin.hive.metastore.thrift.StaticMetastoreLocator.createMetastoreClient(StaticMetastoreLocator.java:109)
... 44 more
Caused by: org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused (Connection refused)
at io.trino.plugin.hive.metastore.thrift.Transport.createRaw(Transport.java:89)
at io.trino.plugin.hive.metastore.thrift.Transport.create(Transport.java:47)
... 48 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
at java.base/java.net.Socket.connect(Socket.java:615)
at io.trino.plugin.hive.metastore.thrift.Transport.createRaw(Transport.java:70)
... 49 more
Suppressed: org.apache.thrift.TException: Failed connecting to Hive metastore: [metastore:9083]
... 45 more
Caused by: org.apache.thrift.transport.TTransportException: metastore:9083: java.net.ConnectException: Connection refused (Connection refused)
at io.trino.plugin.hive.metastore.thrift.Transport.rewriteException(Transport.java:96)
at io.trino.plugin.hive.metastore.thrift.Transport.create(Transport.java:55)
at io.trino.plugin.hive.metastore.thrift.DefaultThriftMetastoreClientFactory.createTransport(DefaultThriftMetastoreClientFactory.java:110)
at io.trino.plugin.hive.metastore.thrift.DefaultThriftMetastoreClientFactory.create(DefaultThriftMetastoreClientFactory.java:97)
at io.trino.plugin.hive.metastore.thrift.StaticMetastoreLocator.getClient(StaticMetastoreLocator.java:123)
at io.trino.plugin.hive.metastore.thrift.StaticMetastoreLocator.createMetastoreClient(StaticMetastoreLocator.java:109)
... 44 more
Caused by: org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused (Connection refused)
at io.trino.plugin.hive.metastore.thrift.Transport.createRaw(Transport.java:89)
at io.trino.plugin.hive.metastore.thrift.Transport.create(Transport.java:47)
... 48 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
at java.base/java.net.Socket.connect(Socket.java:615)
at io.trino.plugin.hive.metastore.thrift.Transport.createRaw(Transport.java:70)
... 49 more
Caused by: org.apache.thrift.transport.TTransportException: metastore:9083: java.net.ConnectException: Connection refused (Connection refused)
at io.trino.plugin.hive.metastore.thrift.Transport.rewriteException(Transport.java:96)
at io.trino.plugin.hive.metastore.thrift.Transport.create(Transport.java:55)
at io.trino.plugin.hive.metastore.thrift.DefaultThriftMetastoreClientFactory.createTransport(DefaultThriftMetastoreClientFactory.java:110)
at io.trino.plugin.hive.metastore.thrift.DefaultThriftMetastoreClientFactory.create(DefaultThriftMetastoreClientFactory.java:97)
at io.trino.plugin.hive.metastore.thrift.StaticMetastoreLocator.getClient(StaticMetastoreLocator.java:123)
at io.trino.plugin.hive.metastore.thrift.StaticMetastoreLocator.createMetastoreClient(StaticMetastoreLocator.java:109)
... 44 more
Caused by: org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused (Connection refused)
at io.trino.plugin.hive.metastore.thrift.Transport.createRaw(Transport.java:89)
at io.trino.plugin.hive.metastore.thrift.Transport.create(Transport.java:47)
... 48 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
at java.base/java.net.Socket.connect(Socket.java:615)
at io.trino.plugin.hive.metastore.thrift.Transport.createRaw(Transport.java:70)
